// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// matTFsph
arma::mat matTFsph(arma::mat X);
RcppExport SEXP _dppca_matTFsph(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(matTFsph(X));
    return rcpp_result_gen;
END_RCPP
}
// matTFwinsor
arma::mat matTFwinsor(arma::mat X, double R);
RcppExport SEXP _dppca_matTFwinsor(SEXP XSEXP, SEXP RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type R(RSEXP);
    rcpp_result_gen = Rcpp::wrap(matTFwinsor(X, R));
    return rcpp_result_gen;
END_RCPP
}
// tau_sph_cpp
arma::mat tau_sph_cpp(arma::mat X);
RcppExport SEXP _dppca_tau_sph_cpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(tau_sph_cpp(X));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dppca_matTFsph", (DL_FUNC) &_dppca_matTFsph, 1},
    {"_dppca_matTFwinsor", (DL_FUNC) &_dppca_matTFwinsor, 2},
    {"_dppca_tau_sph_cpp", (DL_FUNC) &_dppca_tau_sph_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_dppca(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
