#' Adult numeric data
#'
#' A numerical subset of the Adult dataset from the UCI Machine Learning
#' Repository. The original Adult dataset is based on data extracted from
#' the 1994 United States Census database.
#'
#' This package dataset retains five numerical variables:
#' `age`, `education_num`, `capital_gain`, `capital_loss`, and
#' `hours_per_week`. These selected numerical variables contain no missing
#' values in the original data file used here. The resulting dataset contains
#' 32,561 observations.
#'
#' Since the variables have substantially different units and scales, scaling
#' is recommended before applying PCA-based methods.
#'
#' @format A data frame with 32,561 rows and 5 columns:
#' \describe{
#'   \item{age}{Age of the individual.}
#'   \item{education_num}{Number of years of education.}
#'   \item{capital_gain}{Capital gain.}
#'   \item{capital_loss}{Capital loss.}
#'   \item{hours_per_week}{Number of working hours per week.}
#' }
#'
#' @source
#' UCI Machine Learning Repository, Adult dataset.
#' The Adult dataset is licensed under the Creative Commons Attribution 4.0
#' International (CC BY 4.0) license.
#'
#' @references
#' \insertRef{adult}{dppca}
#'
"adult"


#' Five Gaussian clusters
#'
#' A synthetic 20-dimensional Gaussian cluster dataset generated from
#' multivariate normal distributions. It is used as an example for principal
#' component analysis and differentially private PCA visualization.
#'
#' @details
#' The dataset contains 5,000 observations in 20 dimensions. It consists of
#' five groups, with 1,000 observations in each group. The data were generated
#' with seed 123. For each group \eqn{g = 1, \ldots, 5}, observations were
#' sampled independently from a 20-dimensional multivariate normal distribution
#' \eqn{N_{20}(\mu_g, \Sigma_g)}. The first two groups have covariance matrix
#' \eqn{I_{20}}, the third and fourth groups have covariance matrix
#' \eqn{5I_{20}}, and the fifth group has covariance matrix \eqn{8I_{20}}.
#' The group mean vectors differ across selected coordinate blocks, producing
#' both separated and partially overlapping cluster structures.
#'
#' @format A data frame with 5,000 rows and 20 numerical variables. The
#' variables are named `V1`, `V2`, ..., `V20`.
#'
#' @source
#' Generated by the authors of the package.
#'
"gau"


#' Five Gaussian clusters with group labels
#'
#' A grouped version of [`gau`] with an additional group label column.
#'
#' @details
#' The dataset contains the same 5,000 observations and 20 numerical variables
#' as [`gau`], together with a group label column. There are five groups, and
#' each group contains 1,000 observations.
#'
#' @format A data frame with 5,000 rows and 21 columns. The first 20 columns,
#' named `V1`, `V2`, ..., `V20`, are the numerical variables from [`gau`].
#' The last column, `group`, is a group label with values `group1`, `group2`,
#' `group3`, `group4`, and `group5`.
#'
#' @source
#' Generated by the authors of the package.
#'
"gau_g"
