# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matTFsph <- function(X) {
    .Call(`_dppca_matTFsph`, X)
}

matTFwinsor <- function(X, R) {
    .Call(`_dppca_matTFwinsor`, X, R)
}

tau_sph_cpp <- function(X) {
    .Call(`_dppca_tau_sph_cpp`, X)
}

